= REST API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:site-url: /build/asciidoc/html5/
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

ifndef::snippets[]
:snippets: ./build/generated-snippets
:roots: ./build/generated-snippets
endif::[]

== Host
|===
|환경|Host
|LOCAL|http://localhost:8080
|PROD|http://
|===

== User API
회원가입, 메일 인증, 로그인, 토큰 재발급, 로그아웃, 본인 정보, 정보 업데이트, 비밀번호 업데이트 API

=== Member 회원가입 [POST]
operation::members/join[snippets='http-request,request-fields']

=== Member 메일 인증 [GET]
operation::members/email[snippets='http-request,request-parameters,http-response']

=== Member 로그인 [POST]
operation::members/login[snippets='http-request,request-fields,http-response,response-fields']

=== Member 토큰 재발급 [POST]
operation::members/reissue[snippets='http-request,request-fields,http-response,response-fields']

=== Member 로그아웃 [DELETE]
operation::members/logout[snippets='http-request,request-fields,http-response']

=== Member 본인 정보 [GET]
operation::members/me[snippets='http-request,request-headers,http-response,response-fields']

=== Member 정보 업데이트 [PATCH]
operation::members/update[snippets='http-request,request-headers,request-fields,http-response']

=== Member 비밀번호 업데이트 [PATCH]
operation::members/updatePassword[snippets='http-request,request-headers,request-fields,http-response']
